//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPhotos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have canceled the import of the files.
        ///Press Import to start again..
        /// </summary>
        internal static string CancelImport {
            get {
                return ResourceManager.GetString("CancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import complete!
        ///Press Save to database to complete the process!.
        /// </summary>
        internal static string CompleteImport {
            get {
                return ResourceManager.GetString("CompleteImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete..
        /// </summary>
        internal static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to import this files.
        /// </summary>
        internal static string FailImport {
            get {
                return ResourceManager.GetString("FailImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File at location {0} do not exist!.
        /// </summary>
        internal static string FileDontExist {
            get {
                return ResourceManager.GetString("FileDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All (*.BMP;*.JPG;*.GIF;*.JPEG;{0})|*.BMP;*.JPG;*.GIF;*.JPEG;{1}.
        /// </summary>
        internal static string FileImportOption {
            get {
                return ResourceManager.GetString("FileImportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyy.
        /// </summary>
        internal static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} media files found!.
        /// </summary>
        internal static string NMediaFound {
            get {
                return ResourceManager.GetString("NMediaFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} media added to database.
        /// </summary>
        internal static string NMediaImported {
            get {
                return ResourceManager.GetString("NMediaImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media found in directory {0}.
        /// </summary>
        internal static string NoMedia {
            get {
                return ResourceManager.GetString("NoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media found.
        /// </summary>
        internal static string NoMediaFound {
            get {
                return ResourceManager.GetString("NoMediaFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import selected files.
        /// </summary>
        internal static string TittleImport {
            get {
                return ResourceManager.GetString("TittleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media file updated successfully.
        /// </summary>
        internal static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
